### ISSUE TITLE
Get account details

### ISSUE THREAD

**Issue by DajanSles** [DajanSles/GESPRO_Practica_2_Curso_2024_2025#14]
This task get account details used in the project.

**Comment by DavidSantaolalla** [comment]
Consider displaying a summary of recent transactions along with account details to give users quick insights into their latest activity.

**Comment by DajanSles** [comment]
Buena idea. Sí, incluir el saldo podría mejorar la experiencia del usuario. Tal vez también podríamos mostrar el saldo disponible y el saldo total. ¿Qué opinan?

**Comment by DavidSantaolalla** [comment]
> Buena idea. Sí, incluir el saldo podría mejorar la experiencia del usuario. Tal vez también podríamos mostrar el saldo disponible y el saldo total. ¿Qué opinan?

De acuerdo. Mostrar ambos saldos podría ser útil para aquellos con fondos retenidos o pagos pendientes.
