### ISSUE TITLE
Transfer money

### ISSUE THREAD

**Issue by DajanSles** [DajanSles/GESPRO_Practica_2_Curso_2024_2025#15]
Task that allows us to transfer money.

**Comment by DavidSantaolalla** [comment]
Add a confirmation step before finalizing transfers to avoid accidental transactions, and provide estimated transfer time.

**Comment by DavidSantaolalla** [comment]
¿Queremos habilitar transferencias internacionales en esta etapa, o solo transferencias nacionales?

**Comment by DajanSles** [comment]
En esta fase inicial (MVP), creo que deberíamos limitarnos a transferencias nacionales para evitar complejidades adicionales. ¿Todos están de acuerdo?

**Comment by DavidSantaolalla** [comment]
> En esta fase inicial (MVP), creo que deberíamos limitarnos a transferencias nacionales para evitar complejidades adicionales. ¿Todos están de acuerdo?

Sí, tiene sentido. Podemos incluir transferencias internacionales en una versión posterior.
