### ISSUE TITLE
Ask a question/request a service

### ISSUE THREAD

**Issue by DajanSles** [DajanSles/GESPRO_Practica_2_Curso_2024_2025#18]
Part of the project that asks questions.

**Comment by DavidSantaolalla** [comment]
Implement a questions and answers section that suggests answers as users type their question to improve response time for common questions

**Comment by DavidSantaolalla** [comment]
¿Deberíamos integrar esta funcionalidad con el centro de ayuda existente o desarrollar un sistema de preguntas y respuestas independiente?

**Comment by DajanSles** [comment]
Creo que usar el centro de ayuda existente podría ahorrarnos tiempo de desarrollo. ¿Tenemos acceso a su API?

**Comment by DavidSantaolalla** [comment]
> Creo que usar el centro de ayuda existente podría ahorrarnos tiempo de desarrollo. ¿Tenemos acceso a su API?

Sí, podemos consultar con el equipo del centro de ayuda para confirmar si es posible la integración. Les avisaré cuando tenga una respuesta.
